import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Menucategory from '../components/Menucategory';
import Category from '../components/Category';
import Product from '../components/Product';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Foxza - Fashion's Here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/remixicon@4.0.0/fonts/remixicon.css" rel="stylesheet" />
      </Head>


      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.firstPage}>
          <div className={styles.nav1}>
            <p>free shipping on the orders above pkr2500</p>
          </div>

          <div className={styles.nav2}>
            <p><i class="ri-menu-line"></i></p>

            <div className={styles.logoBox}>
              <Image
                src='/logo.jpeg'
                layout='fill'
                objectFit='contain'
                alt="Foxza Logo"
              />
            </div>

            <ul>
              <li><i class="ri-search-line"></i></li>
              <li><i class="ri-shopping-cart-line"></i></li>
              <li><i class="ri-user-line"></i></li>
            </ul>

          </div>

          <div className={styles.nav3}>
            <ul>
              <li>new arrivals</li>
              <li>accessories</li>
              <li>shirts</li>
              <li>Pants</li>
              <li>hoodies</li>
              <li>jackets</li>
              <li>briefs</li>
            </ul>
          </div>



          <div className={styles.menuDiv}>
            <div className={styles.menu}>
              <div className={styles.menuBox}>
                <div className={styles.menuLinks}>
              <div className={styles.menuButton}>
                <button><i class="ri-close-line"></i></button>
              </div>
                  <ul>
                    <li><i class="ri-home-line"></i> home</li>
                    <li><i class="ri-account-circle-line"></i> account</li>
                    <li><i class="ri-login-box-line"></i> login/register</li>
                    <li><i class="ri-download-line"></i> download app</li>
                    <li><i class="ri-contacts-book-line"></i> contact us</li>
                    <li><i class="ri-article-line"></i> terms & conditions</li>
                    <li><i class="ri-shield-star-line"></i> privacy policy</li>
                  </ul>
                </div>
                <div className={styles.menuCategories}>
                  <Menucategory categoryName="t-shirts" imageUrl="/Product Categories/tshirts.png" />
                  <Menucategory categoryName="pants" imageUrl="/Product Categories/pants.png" />
                  <Menucategory categoryName="leather jackets" imageUrl="/Product Categories/leather jacket.png" />
                  <Menucategory categoryName="hoodies" imageUrl="/Product Categories/hoodies.png" />
                  <Menucategory categoryName="sweat shirts" imageUrl="/Product Categories/sweat shirts.png" />
                  <Menucategory categoryName="winter jackets" imageUrl="/Product Categories/winter jackets.png" />
                  <Menucategory categoryName="denim" imageUrl="/Product Categories/denim.png" />
                  <Menucategory categoryName="casual shirts" imageUrl="/Product Categories/casual shirts.png" />
                  <Menucategory categoryName="dress shirts" imageUrl="/Product Categories/dress shirts.png" />
                  <Menucategory categoryName="dress pants" imageUrl="/Product Categories/dress pants.png" />
                  <Menucategory categoryName="boxers" imageUrl="/Product Categories/boxers.png" />
                  <Menucategory categoryName="accessories" imageUrl="/Product Categories/accessories.png" />
                </div>
              </div>
            </div>
          </div>



          <div className={styles.frontDisplay}>
            <div className={styles.sale}><p>w</p><p>i</p><p>n</p><p>t</p><p>e</p><p>r</p><p>&nbsp;</p><p>s</p><p>a</p><p>l</p><p>e</p></div>
            <div className={styles.displayInner}>
              <div className={styles.diLeft}>
                <h2><i class="ri-circle-fill"></i> winter sale</h2>
                <h1>50% off</h1>
                <h3>starting from</h3>
                <h2>31 - dec - 2023</h2>
                <button>buy now</button>
                <div className={styles.rotatingIB}>
                  <Image
                    src='/spinner.png'
                    layout='fill'
                    objectFit='cover'
                    alt="Foxza Logo"
                  />
                </div>
              </div>
              <div className={styles.diRight}>
                <div className={styles.imageBox}>
                  <Image
                    src='/frontPic.jpg'
                    layout='fill'
                    objectFit='cover'
                    alt="Foxza Logo"
                  />
                </div>
              </div>
            </div>
            <div className={styles.sale}><p>w</p><p>i</p><p>n</p><p>t</p><p>e</p><p>r</p><p>&nbsp;</p><p>s</p><p>a</p><p>l</p><p>e</p></div>
          </div>


        </div>


        <div className={styles.secondPage}>
          <div className={styles.bannerImage}>
            <Image
              src='/firstBanner.png'
              layout='fill'
              objectFit='cover'
              alt="Foxza Logo"
            />
          </div>
        </div>




        <div className={styles.thirdPage}>
          <div className={styles.categoriesPage}>
            <h1><i class="ri-circle-fill"></i> our popular categories</h1>
            <Category categoryName="t-shirts" imageUrl="/Product Categories/tshirts.png" />
            <Category categoryName="pants" imageUrl="/Product Categories/pants.png" />
            <Category categoryName="leather jackets" imageUrl="/Product Categories/leather jacket.png" />
            <Category categoryName="hoodies" imageUrl="/Product Categories/hoodies.png" />
            <Category categoryName="sweat shirts" imageUrl="/Product Categories/sweat shirts.png" />
            <Category categoryName="winter jackets" imageUrl="/Product Categories/winter jackets.png" />
            <Category categoryName="denim" imageUrl="/Product Categories/denim.png" />
            <Category categoryName="casual shirts" imageUrl="/Product Categories/casual shirts.png" />
            <Category categoryName="dress shirts" imageUrl="/Product Categories/dress shirts.png" />
            <Category categoryName="dress pants" imageUrl="/Product Categories/dress pants.png" />
            <Category categoryName="boxers" imageUrl="/Product Categories/boxers.png" />
            <Category categoryName="accessories" imageUrl="/Product Categories/accessories.png" />
          </div>
        </div>





        <div className={styles.forthPage}>
          <div className={styles.productPageOne}>
            <h1><i class="ri-circle-fill"></i> our latest additions</h1>
            <Product productType="latest" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/tshirts.png" />
            <Product productType="latest" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/pants.png" />
            <Product productType="latest" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/leather jacket.png" />
            <Product productType="latest" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/hoodies.png" />
            <Product productType="latest" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/sweat shirts.png" />
            <Product productType="latest" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/winter jackets.png" />
            <Product productType="latest" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/denim.png" />
            <Product productType="latest" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/casual shirts.png" />
          </div>
        </div>






        <div className={styles.fifthPage}>
          <div className={styles.productPageTwo}>
            <h1><i class="ri-circle-fill"></i> our produts on sale</h1>
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/tshirts.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/pants.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/leather jacket.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/hoodies.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/sweat shirts.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/winter jackets.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/denim.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/casual shirts.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/denim.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/casual shirts.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/denim.png" />
            <Product productType="50% off" productPrice="rs2500" productName="Lorem ipsum dolor sit amet, consectetur adipiscing elit" imageUrl="/Product Categories/casual shirts.png" />
          </div>
        </div>






        <div className={styles.sixthPage}>
          <div className={styles.bannerImage}>
            <Image
              src='/voucher.png'
              layout='fill'
              objectFit='contain'
              alt="Foxza Logo"
            />
          </div>
        </div>






        <div className={styles.seventhPage}>
          <div className={styles.socialMediaLinks}>
            <h1><i class="ri-circle-fill"></i> connect with us through</h1>
            <ul>
              <li><i class="ri-arrow-right-up-line"></i> facebook</li>
              <li><i class="ri-arrow-right-up-line"></i> instagram</li>
              <li><i class="ri-arrow-right-up-line"></i> youtube</li>
              <li><i class="ri-arrow-right-up-line"></i> tiktok</li>
              <li><i class="ri-arrow-right-up-line"></i> pinterest</li>
            </ul>
          </div>
        </div>







        <div className={styles.footerPage}>
          <div className={styles.branding}>
            <h1>foxza.</h1>
            <ul>
              <li>account</li>
              <li>login/register</li>
              <li>download app</li>
              <li>contact us</li>
              <li>terms & conditions</li>
              <li>privacy policy</li>
            </ul>
            <p>NTN Number: 1234567-8</p>
          </div>
          <div className={styles.footerCopyright}>
            <h3>Made with '🤍' by <a href="http://developer.growfastrevolution.com/" target="_blank" rel="noopener noreferrer">ABE k27</a></h3>
            <h3>Copyright © 2023 Foxza | All right reserved</h3>
          </div>
        </div>




      </main>
    </>
  )
}
